### ISSUE TITLE
集成后弹窗提示错误

### ISSUE THREAD

**Issue by wzlee** [18506711722/AION-swagger2-spring-boot-starter#1]
![image](https://user-images.githubusercontent.com/4182865/36011003-662bc6c6-0d8f-11e8-8b00-ad7771947b27.png)

**Comment by 18506711722** [comment]
@EnableSwagger2  需要在配置类上加上这个注解，我只是写着玩耍的

**Comment by 18506711722** [comment]
application.yml    添加配置  
swagger2:
  enable: true
